# Generated by Django 5.0.6 on 2026-04-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('GUARD', 'Security Guard'), ('RESIDENT', 'Resident')], default='GUARD', max_length=10),
        ),
    ]
