# Generated by Django 5.0.6 on 2026-04-09 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_residents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resident',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resident',
            name='sex',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='resident',
            name='street_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='resident',
            name='street_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resident',
            name='suffix',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='resident',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resident',
            name='valid_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='resident_ids/'),
        ),
        migrations.AddField(
            model_name='resident',
            name='valid_id_type',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
