# Generated by Django 5.0.6 on 2026-04-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_resident_age_resident_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='approval_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
