# Generated by Django 5.0.6 on 2026-04-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_resident_approval_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='valid_id_type',
            field=models.CharField(blank=True, choices=[('', '-- Select Valid ID --'), ('PHILSYS_ID', 'PhilSys National ID'), ('PASSPORT', 'Passport'), ('DRIVERS_LICENSE', "Driver's License"), ('UMID', 'UMID'), ('SSS_ID', 'SSS ID'), ('GSIS_ECARD', 'GSIS eCard'), ('PRC_ID', 'PRC ID'), ('POSTAL_ID', 'Postal ID'), ('VOTERS_ID', "Voter's ID"), ('SENIOR_CITIZEN_ID', 'Senior Citizen ID'), ('PWD_ID', 'PWD ID'), ('TIN_ID', 'TIN ID'), ('NBI_CLEARANCE', 'NBI Clearance'), ('POLICE_CLEARANCE', 'Police Clearance'), ('BARANGAY_ID', 'Barangay ID'), ('OWWA_ID', 'OWWA ID'), ('SEAMANS_BOOK', "Seaman's Book"), ('SCHOOL_ID', 'School ID'), ('COMPANY_ID', 'Company ID'), ('OTHER_GOVERNMENT_ID', 'Other Government Issued ID')], max_length=80),
        ),
    ]
