# Generated by Django 5.0.6 on 2026-03-04 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('host_name', models.CharField(blank=True, help_text='Name of resident being visited', max_length=200)),
                ('plate_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('vehicle_type', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_visitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visitors',
                'ordering': ['-created_at'],
            },
        ),
    ]
