# Generated by Django 5.0.6 on 2026-04-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_blacklistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistentry',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blacklistentry',
            name='tag',
            field=models.CharField(choices=[('WATCHLIST', 'Watchlist'), ('HIGH_RISK', 'High Risk'), ('TEMP_BLOCK', 'Temporary Block')], default='WATCHLIST', max_length=20),
        ),
    ]
