# Generated by Django 5.0.6 on 2026-04-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_blacklistentry_remarks_blacklistentry_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='vehicle_type_other',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
