# Generated by Django 5.0.6 on 2026-09-04 02:44

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0006_visitor_visitor_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blacklistentry',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='blacklistentry',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blacklistentry',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blacklistentry',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='blacklistentry',
            name='plate_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='blacklistentry',
            name='tag',
            field=models.CharField(choices=[('WATCHLIST', 'Watchlist'), ('HIGH_RISK', 'High Risk')], default='WATCHLIST', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='blacklistentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('plate_number',), name='unique_active_blacklist_plate'),
        ),
    ]
