# Generated by Django 5.0.6 on 2026-03-04 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(db_index=True, max_length=20)),
                ('entry_type', models.CharField(choices=[('RESIDENT', 'Resident'), ('VISITOR', 'Visitor'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('status', models.CharField(choices=[('TIME_IN', 'Time In'), ('TIME_OUT', 'Time Out')], max_length=10)),
                ('source', models.CharField(choices=[('CAMERA', 'Camera'), ('MANUAL', 'Manual')], default='CAMERA', max_length=10)),
                ('resident_name', models.CharField(blank=True, max_length=200)),
                ('visitor_name', models.CharField(blank=True, max_length=200)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='snapshots/')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vehicle_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['plate_number', 'timestamp'], name='vehicle_log_plate_n_973bf9_idx')],
            },
        ),
    ]
