# Generated by Django 5.0.6 on 2026-03-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelog',
            name='camera_role',
            field=models.CharField(
                blank=True,
                choices=[('ENTRY_CAM', 'Entry Camera'), ('EXIT_CAM', 'Exit Camera'), ('UNKNOWN', 'Unknown')],
                db_index=True,
                default='UNKNOWN',
                max_length=20,
            ),
        ),
    ]
