# Generated by Django 5.0.6 on 2026-04-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_vehiclelog_camera_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelog',
            name='entry_type',
            field=models.CharField(choices=[('RESIDENT', 'Resident'), ('VISITOR', 'Visitor'), ('UNKNOWN', 'Unknown')], default='VISITOR', max_length=10),
        ),
    ]
